name: "Public IP address"
description: "returns the runner's public IP address"
inputs:
  retry-times:
    required: false
    default: "10"
  max-time:
    required: false
    default: "10"
  retry-max-time:
    required: false
    default: "40"
outputs:
  ipv4:
    description: "Runner's public v4 IP address"
    value: ${{ steps.ip.outputs.ipv4 }}
runs:
  using: "composite"
  steps:
    - name: Get GitHub runner public IP address
      id: ip
      shell: bash
      run: |
        echo "ipv4=$(curl -s --max-time ${{ inputs.max-time }} --retry ${{ inputs.retry-times }} --retry-delay 0 --retry-max-time ${{ inputs.retry-max-time }} https://api.ipify.org/\?format\=txt)" >> $GITHUB_OUTPUT