name: Build Application

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

concurrency: job-${{ github.sha }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: |
          echo "finished building app"