name: Build Application

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

concurrency: job-${{ github.sha }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub runner public ip address
        id: ip
        run: |
          echo "ipv4=$(curl --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 https://api.ipify.org/\?format\=txt)" >> $env:GITHUB_OUTPUT
    
      - name: setup
        run: |
          echo "finished building app with agent ip ${{ steps.ip.outputs.ipv4 }}"