name: Deploy Application

on:
  workflow_dispatch:
  push:
    tags:
    - tst
    - ppd
    - prd

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: job-${{ github.sha }}
    name: "Deploy"
    environment: ${{ github.ref_name }}
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v3
      - name: Extract version from sha
        id: website
        run: |
          git fetch --tags --force
          $version=$(git tag --list '*.*.*' --points-at ${{ github.sha }} --sort=version:refname | tail -n1)
          if ($version.StartsWith("v")) {
            $version = $version.Substring(1)
          }
          echo "version=$version" >> $env:GITHUB_OUTPUT      

      - name: Deploy web app
        run: |
          echo "ENV: ${{ env }}"
          echo "TAG: ${{ github.ref_name }}"
          echo "Deploying: ${{ secrets.PUBLISH_PROFILE }}"
          echo ${{ secrets.PUBLISH_PROFILE }} | sed 's/./& /g'
          echo "Build Website Version: ${{ steps.website.outputs.version }}"
